/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWebhooksIndexRouteImport } from './routes/dashboard/webhooks/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardKnowledgeIndexRouteImport } from './routes/dashboard/knowledge/index'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard/customers/index'
import { Route as DashboardConversationsIndexRouteImport } from './routes/dashboard/conversations/index'
import { Route as DashboardAutomationsIndexRouteImport } from './routes/dashboard/automations/index'
import { Route as DashboardSettingsTeamRouteImport } from './routes/dashboard/settings/team'
import { Route as DashboardSettingsPipelineRouteImport } from './routes/dashboard/settings/pipeline'
import { Route as DashboardSettingsCustomFieldsRouteImport } from './routes/dashboard/settings/custom-fields'
import { Route as DashboardKnowledgeNewRouteImport } from './routes/dashboard/knowledge/new'
import { Route as DashboardCustomersCustomerIdRouteImport } from './routes/dashboard/customers/$customerId'
import { Route as DashboardAutomationsFlowIdRouteImport } from './routes/dashboard/automations/$flowId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksIndexRoute = DashboardWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeIndexRoute = DashboardKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsIndexRoute =
  DashboardConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAutomationsIndexRoute =
  DashboardAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsTeamRoute = DashboardSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsPipelineRoute =
  DashboardSettingsPipelineRouteImport.update({
    id: '/settings/pipeline',
    path: '/settings/pipeline',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsCustomFieldsRoute =
  DashboardSettingsCustomFieldsRouteImport.update({
    id: '/settings/custom-fields',
    path: '/settings/custom-fields',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardKnowledgeNewRoute = DashboardKnowledgeNewRouteImport.update({
  id: '/knowledge/new',
  path: '/knowledge/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersCustomerIdRoute =
  DashboardCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAutomationsFlowIdRoute =
  DashboardAutomationsFlowIdRouteImport.update({
    id: '/automations/$flowId',
    path: '/automations/$flowId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/automations/$flowId': typeof DashboardAutomationsFlowIdRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/dashboard/knowledge/new': typeof DashboardKnowledgeNewRoute
  '/dashboard/settings/custom-fields': typeof DashboardSettingsCustomFieldsRoute
  '/dashboard/settings/pipeline': typeof DashboardSettingsPipelineRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/automations/': typeof DashboardAutomationsIndexRoute
  '/dashboard/conversations/': typeof DashboardConversationsIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/knowledge/': typeof DashboardKnowledgeIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/automations/$flowId': typeof DashboardAutomationsFlowIdRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/dashboard/knowledge/new': typeof DashboardKnowledgeNewRoute
  '/dashboard/settings/custom-fields': typeof DashboardSettingsCustomFieldsRoute
  '/dashboard/settings/pipeline': typeof DashboardSettingsPipelineRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/automations': typeof DashboardAutomationsIndexRoute
  '/dashboard/conversations': typeof DashboardConversationsIndexRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/webhooks': typeof DashboardWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/automations/$flowId': typeof DashboardAutomationsFlowIdRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/dashboard/knowledge/new': typeof DashboardKnowledgeNewRoute
  '/dashboard/settings/custom-fields': typeof DashboardSettingsCustomFieldsRoute
  '/dashboard/settings/pipeline': typeof DashboardSettingsPipelineRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/automations/': typeof DashboardAutomationsIndexRoute
  '/dashboard/conversations/': typeof DashboardConversationsIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/knowledge/': typeof DashboardKnowledgeIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/'
    | '/dashboard/automations/$flowId'
    | '/dashboard/customers/$customerId'
    | '/dashboard/knowledge/new'
    | '/dashboard/settings/custom-fields'
    | '/dashboard/settings/pipeline'
    | '/dashboard/settings/team'
    | '/dashboard/automations/'
    | '/dashboard/conversations/'
    | '/dashboard/customers/'
    | '/dashboard/knowledge/'
    | '/dashboard/settings/'
    | '/dashboard/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard'
    | '/dashboard/automations/$flowId'
    | '/dashboard/customers/$customerId'
    | '/dashboard/knowledge/new'
    | '/dashboard/settings/custom-fields'
    | '/dashboard/settings/pipeline'
    | '/dashboard/settings/team'
    | '/dashboard/automations'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/webhooks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/'
    | '/dashboard/automations/$flowId'
    | '/dashboard/customers/$customerId'
    | '/dashboard/knowledge/new'
    | '/dashboard/settings/custom-fields'
    | '/dashboard/settings/pipeline'
    | '/dashboard/settings/team'
    | '/dashboard/automations/'
    | '/dashboard/conversations/'
    | '/dashboard/customers/'
    | '/dashboard/knowledge/'
    | '/dashboard/settings/'
    | '/dashboard/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks/': {
      id: '/dashboard/webhooks/'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks/'
      preLoaderRoute: typeof DashboardWebhooksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge/': {
      id: '/dashboard/knowledge/'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge/'
      preLoaderRoute: typeof DashboardKnowledgeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations/': {
      id: '/dashboard/conversations/'
      path: '/conversations'
      fullPath: '/dashboard/conversations/'
      preLoaderRoute: typeof DashboardConversationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automations/': {
      id: '/dashboard/automations/'
      path: '/automations'
      fullPath: '/dashboard/automations/'
      preLoaderRoute: typeof DashboardAutomationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/team': {
      id: '/dashboard/settings/team'
      path: '/settings/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/pipeline': {
      id: '/dashboard/settings/pipeline'
      path: '/settings/pipeline'
      fullPath: '/dashboard/settings/pipeline'
      preLoaderRoute: typeof DashboardSettingsPipelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/custom-fields': {
      id: '/dashboard/settings/custom-fields'
      path: '/settings/custom-fields'
      fullPath: '/dashboard/settings/custom-fields'
      preLoaderRoute: typeof DashboardSettingsCustomFieldsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge/new': {
      id: '/dashboard/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/dashboard/knowledge/new'
      preLoaderRoute: typeof DashboardKnowledgeNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/$customerId': {
      id: '/dashboard/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof DashboardCustomersCustomerIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automations/$flowId': {
      id: '/dashboard/automations/$flowId'
      path: '/automations/$flowId'
      fullPath: '/dashboard/automations/$flowId'
      preLoaderRoute: typeof DashboardAutomationsFlowIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAutomationsFlowIdRoute: typeof DashboardAutomationsFlowIdRoute
  DashboardCustomersCustomerIdRoute: typeof DashboardCustomersCustomerIdRoute
  DashboardKnowledgeNewRoute: typeof DashboardKnowledgeNewRoute
  DashboardSettingsCustomFieldsRoute: typeof DashboardSettingsCustomFieldsRoute
  DashboardSettingsPipelineRoute: typeof DashboardSettingsPipelineRoute
  DashboardSettingsTeamRoute: typeof DashboardSettingsTeamRoute
  DashboardAutomationsIndexRoute: typeof DashboardAutomationsIndexRoute
  DashboardConversationsIndexRoute: typeof DashboardConversationsIndexRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardKnowledgeIndexRoute: typeof DashboardKnowledgeIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardWebhooksIndexRoute: typeof DashboardWebhooksIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAutomationsFlowIdRoute: DashboardAutomationsFlowIdRoute,
  DashboardCustomersCustomerIdRoute: DashboardCustomersCustomerIdRoute,
  DashboardKnowledgeNewRoute: DashboardKnowledgeNewRoute,
  DashboardSettingsCustomFieldsRoute: DashboardSettingsCustomFieldsRoute,
  DashboardSettingsPipelineRoute: DashboardSettingsPipelineRoute,
  DashboardSettingsTeamRoute: DashboardSettingsTeamRoute,
  DashboardAutomationsIndexRoute: DashboardAutomationsIndexRoute,
  DashboardConversationsIndexRoute: DashboardConversationsIndexRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardKnowledgeIndexRoute: DashboardKnowledgeIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardWebhooksIndexRoute: DashboardWebhooksIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
